schema:
  - './src/temp/GraphQLIntrospectionResult.json'
documents: 'src/**/*.sitecore.graphql'
plugins:
  - typescript
  - typescript-operations
  - typed-document-node
cacheDir: .generated
config:
    useIndexSignature: true
