name: Deploy azure functions project to function app

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: funcjssnextjsonazure    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './packages/jss-nextjs-app-azure-functions'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x)
  JSSAPPSOURCE: './packages/jss-nextjs-app'
  JSSAPPDEST: 'https://storageaccountnextj9121.file.core.windows.net/funcjssnextjsonazurea512/site/nextsrcazcopy?{SECRETSASTOKEN}'

jobs:
  build-and-deploy:
    env:
      SITECORE_API_HOST: https://erwinazurejss.loca.lt
      SITECORE_API_KEY: ${{ secrets.SITECORE_API_KEY }}
      PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
      JSS_EDITING_SECRET: ${{ secrets.JSS_EDITING_SECRET }}
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: pwsh
      run: |
        lerna bootstrap
        npm run build:jssnextjs
        popd

    - name: Install azcopy
      uses: kheiakiyama/install-azcopy-action@v1.0.3

    # Copy jss-nextjs-app
    - uses: actions/checkout@v2
    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'
    - run: azcopy_v10 '{JSSAPPSOURCE}' '{JSSAPPDEST}' --recursive --set-content-type
    
    # - name: 'Run Azure Functions Action'
    #   uses: Azure/functions-action@v1
    #   id: fa
    #   with:
    #     scm-do-build-during-deployment: true
    #     enable-oryx-build: true
    #     app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
    #     package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}