name: Deploy azure functions project to function app

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: funcjssnextjsonazure    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './packages/jss-nextjs-app-azure-functions'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x)
  JSSAPPSOURCE: './packages/jss-nextjs-app'
  JSSAPPDEST: 'https://storageaccountnextj9121.file.core.windows.net/funcjssnextjsonazurea512/site/nextsrcazcopy'

jobs:
  build-and-deploy:
    env:
      SITECORE_API_HOST: https://erwinazurejss.loca.lt
      SITECORE_API_KEY: ${{ secrets.SITECORE_API_KEY }}
      PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
      JSS_EDITING_SECRET: ${{ secrets.JSS_EDITING_SECRET }}
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install azcopy
      uses: kheiakiyama/install-azcopy-action@v1.0.3

    - name: Azure CLI Action
      uses: Azure/cli@1.0.4

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az functionapp deployment user set --user-name funcjssnextjsonazure\$funcjssnextjsonazure --password lvKHHtuwroQ6d6poDMHhc5RaWcvcMWu8LiodNkH5x4cXwmwTfwdhQlSS7HsQ
          az functionapp deployment source config-zip -g nextjsonazure -n funcjssnextjsonazure --src dist.zip --subscription "MI - Test" --no-zip

    - name: 'Resolve Project Dependencies Using Npm'
      shell: pwsh
      run: |
        lerna bootstrap
        npm run build:jssnextjs
        popd

    - uses: kheiakiyama/install-azcopy-action@v1
      with:
        version: 'v10'
    - run: azcopy_v10 copy '${{ env.JSSAPPSOURCE }}' '${{ env.JSSAPPDEST }}?${{ secrets.SECRETSASTOKEN }}' --recursive
    
    # Copy jss-nextjs-app
    # - uses: actions/checkout@v2
    # - name: 'Run Azure Functions Action'
    #   uses: Azure/functions-action@v1
    #   id: fa
    #   with:
    #     scm-do-build-during-deployment: true
    #     enable-oryx-build: true
    #     app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
    #     package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} 